### ISSUE TITLE
[PE-D][Tester A] Table of Contents in UG buggy

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F13-4/tp#222] opened 2024-11-08 20:31 UTC
![image.png](https://raw.githubusercontent.com/fusin02/ped/main/files/7a34873d-cf03-4f9c-866f-0db2993a51ed.png)

The TOC seems a bit buggy here in the PDF

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: fusin02/ped#10

**Comment by trpmy** [comment] 2024-11-09 06:16
assigning this because i think this is a markbind layout issue?

**Comment by reginateh** [comment] 2024-11-10 08:15
Duplicate of #187

**Comment by trpmy** [comment] 2024-11-11 04:48
See #187

**Closed by trpmy** 2024-11-11 04:48 UTC
